min_pep_length: 6
max_pep_length: 52
min_mz_range: 200
max_mz_range: 4000
enzyme : 'trypsin_full'
input_pep: 'test_spectronaut_pep_out.tsv'
input_prot: 'test_spectronaut_prot_out.tsv'
input_fasta: 'test_sequence.fa'
